### ISSUE TITLE
how to Set the path of environment variable ?

### ISSUE THREAD

**Issue by Nsseirat** [Samsung/grunt-cordova-sectv#11]
I am using the plugin for the first time and i have reached the  How to build and package  step .

can you please give more details on Set the path of environment variable for sectv-tizen case 2 and tv-webos , i didnt under stand where to put the "tizen" command and "ares" command.

Fatal error: The command "tizen" failed. Make sure you have the latest Tizen SDK installed, and the "tizen" command (inside the tools/ide/bin folder) is added to your path.

Fatal error: The command "ares" failed. Make sure you have the latest Webos SDK installed, and the "ares" command (inside the CLI folder) is added to your path.

**Comment by prozanne** [comment]
Hi :bread: 
First, let me know you installed tizen SDK or webos SDK.
If not, please install below SDKs.

http://developer.samsung.com/tv/develop/getting-started/setup-sdk/installation-of-tv-sdk
http://webostv.developer.lge.com/sdk/download/download-sdk/

And then,
you need to set environment variable. It has different methods for each platforms.
If you have an window OS, follow this guide. https://www.youtube.com/watch?v=bEroNNzqlF4
Or macOS/linux, follow this guide. https://www.youtube.com/watch?v=-cASjkF94dc

You can only set environment variable path with installed path for tizen SDK or webOS.

In my case, I use windows...
So did it like below.
![image](https://user-images.githubusercontent.com/1733182/27889235-f30bb422-6225-11e7-960b-4971b7f0decc.png)
C:\tizen-sdk\tools\ide\bin;C:\webOS_TV_SDK\CLI;

Thanks.

**Comment by Nsseirat** [comment]
thank you for responding , i have checked the above and i have the SDK for webos and i 
installed tizen SDK using Tizen package manager, 

and i have added the path as following ( C:\tizen-studio\tools\ide\bin; C:\webOS_SDK\CLI ) , and i still have the same error when i run ( grunt sectv-build:tv-webos , grunt sectv-build:sectv-tizen) 

Error :Fatal error: The command "ares" failed. Make sure you have the latest Webos SDK installed, and the "ares" command (inside the CLI folder) is added to your path.

Fatal error: The command "tizen" failed. Make sure you have the latest Tizen SDK installed, and the "tizen" command (inside the tools/ide/bin folder) is added to your path.

am using windows 10.

another question :  for sectv-tizen Modify Gruntfile.js i got the profile name but i cant find the path , what you mean by ( \<yourWorkspace\> ) the path that contains the cordova project or the path where tizen studio create its project , its kind silly question but am lost.

sorry for bothering you and thank you for your time.

**Comment by Nsseirat** [comment]
thank you for your time it is working now for , the problem was that cmd didn't load the system variables until i logged out from my windows profile and sign in a gain.
