### ISSUE TITLE
Fatal error: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by GianhTran** [Samsung/grunt-cordova-sectv#19]
After I completed all step in https://github.com/Samsung/grunt-cordova-sectv/blob/master/README.md#how-to-build-and-package-the-application-by-platforms

I run 
 `grunt sectv-build:sectv-tizen`

and I face a error as below

```
BUILD SUCCESSFUL
Output path : /home/framgia/TOAST/sampleMedia/platforms/sectv-tizen/www/.buildResult
Excluded : [.build/*, .build, .sign/*, .sign, webUnitTest/*, webUnitTest, .externalToolBuilders/*, .externalToolBuilders, .buildResult/*, .buildResult, .settings/*, .settings, .package/*, .package, .tproject, .project, .sdk_delta.info, .rds_delta, *.wgt, .tizen-ui-builder-tool.xml]
Total time: 00:00:00.773
Author certficate: /home/framgia/tizen-studio-data/keystore/author/MyCertification.p12
Distributor1 certificate : /home/framgia/tizen-studio/tools/certificate-generator/certificates/distributor/tizen-distributor-signer.p12
Excludes File Pattern: {.manifest.tmp, .delta.lst}
Ignore File: /home/framgia/TOAST/sampleMedia/platforms/sectv-tizen/www/.buildResult/.manifest.tmp
Package File Location: /home/framgia/TOAST/sampleMedia/platforms/sectv-tizen/www/.buildResult/myapp.wgt
Fatal error: Cannot read property 'match' of undefined
```

I still have a output `.wgt` but I fear that something is wrong.
Can I have any help, any response would be appreciated.

**Comment by mohannadelqadi** [comment]
Samsung have the worst documentation and support

**Comment by bounmed** [comment]
I am facing the same problem did you find any solution?

**Comment by yurtaev** [comment]
@bounmed https://github.com/Samsung/grunt-cordova-sectv/pull/17

**Comment by mohannadelqadi** [comment]
When I tried the outcome of the build it was working fine, even with the error that happens.
But I am afraid that there are things not clear on the development and it will start coming up on the production.

**Comment by dseeker** [comment]
this is the function that's not executing
https://github.com/Samsung/grunt-cordova-sectv/blob/master/tasks/packager/sectv-tizen.js#L359-L368
it's using result.stdout, but there is no such key, need to change it to result.output
I've opened a PR to fix this, please test on your systems and let me know if this helped

**Comment by prozanne** [comment]
We have merged it.
Thanks!
And please try to pull the latest codes again.
